name: harmony_login_ui
description: Harmony Login UI Elements.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0

publish_to: https://unpub.cloud.6thsolution.tech

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  flutter_svg: any
  harmony_auth:
    hosted:
      name: harmony_auth
      url: https://unpub.cloud.6thsolution.tech
    version: ^1.0.0
  harmony_fire:
    hosted:
      name: harmony_fire
      url: https://unpub.cloud.6thsolution.tech
    version: ^1.0.0
  harmony_login:
    hosted:
      name: harmony_login
      url: https://unpub.cloud.6thsolution.tech
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  mocktail: any

flutter:
  uses-material-design: true
  assets:
    - asset/image/harmony_login_ui_apple.svg
    - asset/image/harmony_login_ui_email.svg
    - asset/image/harmony_login_ui_facebook.svg
    - asset/image/harmony_login_ui_google.svg
