name: harmony_login_ui
description: Harmony Login UI Elements.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0

# remove this to publish
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  flutter_svg: any
  harmony_auth:
    path: ../harmony_auth/
  harmony_fire:
    path: ../harmony_fire/
  harmony_login:
    path: ../harmony_login/

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  mocktail: any
