name: harmony_auth
description: Harmony Low-Level Authentication and Token Management Mechanism.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0

# remove this to publish
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  dio: ^4.0.0
  shared_preferences: ^2.0.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  mocktail: any
