name: example
description: Harmony Example.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  flutter_svg: any
  harmony_log:
    path: ../harmony_log/
  harmony_auth:
    path: ../harmony_auth/
  harmony_fire:
    path: ../harmony_fire/
  harmony_login:
    path: ../harmony_login/
  harmony_login_ui:
    path: ../harmony_login_ui/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/email.svg
    - asset/image/google.svg
    - asset/image/apple.svg
    - asset/image/facebook.svg
