name: example
description: Harmony Example.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  harmony_log:
    path: ../harmony_log/
  harmony_auth:
    path: ../harmony_auth/
  harmony_fire:
    path: ../harmony_fire/
  harmony_login:
    path: ../harmony_login/
  harmony_login_ui:
    path: ../harmony_login_ui/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/apple.png
    - asset/image/email.png
    - asset/image/facebook.png
    - asset/image/google.png
    - asset/image/verified_email.png
    - asset/image/verify_email.png
