name: harmony_login
description: Harmony Login Mechanism.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 1.0.0

publish_to: https://unpub.cloud.6thsolution.tech

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  mocktail: any
