name: harmony_network
description: harmony's command line tool to generate a dio based flutter network client from an openapi sepcifications yaml file
version: 0.2.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0  

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

executables:
  harmony_network: main