name: harmony_log
description: Harmony Logging Mechanism. It has varous implementations of filters and outputs.
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  pedantic: ^1.0.0
  uuid: ^3.0.0
