name: harmony_log
description: Harmony Logging Mechanism.
version: 0.1.0
homepage: https://github.com/6thsolution/harmony
repository: https://github.com/6thsolution/harmony

# todo remove this
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  pedantic: ^1.11.0
