targets:
  $default:
    builders:
      harmony_network_generator|harmony_network:
        enabled: true

builders:
  harmony_network_generator:
#    runs_before: ["jaguarRetrofitBuilder"]
    target: ":harmony_network_generator"
    import: "package:harmony_network_generator/src/builder.dart"
    builder_factories: ["openApiClientSdk"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
